parameters:
    kernel.secret: SecretToken
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     Symfony
    database_user:     root
    database_password: ~
    database_chartset: UTF-8
    database_server_version: 5.6